trigger:
- none


#--------------Variables---------------------------------------------------------
variables:
- group: Umbraco_Deploy_Env_Staging
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildParameters.ArtifactName
  value: UmbrV1
- name: BuildConfiguration
  value: 'Release'
- name: BuildPlatform
  value:  'Any CPU'



#--------------Resources---------------------------------------------------------
resources:
  repositories:
  - repository: githubRepo
    type: github
    ref: '$(github_branch)'
    endpoint: 'github.com_anilkdhiman5'
    name: 'wmcadigital/wmre-umbraco-cms'



#--------------Stages---------------------------------------------------------
stages:
- stage: A
  displayName: 'Create Umbraco Artifact'
  jobs:
    - job: Job_A1
      displayName: Agent job A1
      pool:
        vmImage: vs2017-win2016
      steps:
      - checkout: self
      - script: 'dir D:\a\1\s\'
      - task: CopyFiles@2
        displayName: 'Copy Required File(s)' 
        inputs:
          contents: 'D:\a\1\s\WebCms\umbraco\SetDBConnectionString.ps1'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - checkout: githubRepo
      - script: 'dir D:\a\1\s\WebCms\'
      - task: AzurePowerShell@4
        displayName: 'Set Db SqlClient Version'
        inputs:
          azureSubscription: '$(subscriptionName)'
          ScriptPath: 'D:\a\1\s\WebCms\Database\SetDBConnectionString.ps1'
          ScriptArguments: >-
             -xmlFileName "D:\a\1\s\wmre-umbraco-cms\wmrecms.web\ConnectionStrings.config"
             -serverName '$(servers_umbraco_name)'
             -databaseName '$(servers_umbraco_name_db)'
             -userId '$(sqladminlogin)'
             -password '$(sqladminpassword)'
          azurePowerShellVersion: LatestVersion

      - task: NuGetToolInstaller@0
        displayName: Use NuGet 4.4.1
        inputs:
          versionSpec: 4.4.1
      - task: NuGetCommand@2
        displayName: NuGet restore
        inputs:
          solution: $(BuildParameters.solution)
      - task: VSBuild@1
        displayName: Build solution
        inputs:
          solution: $(BuildParameters.solution)
          msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
          clean: true
    
    #--------------Publish Jobs---------------------------------------------------------
      - task: PublishSymbols@2
        displayName: Publish symbols path
        continueOnError: True
        inputs:
          SearchPattern: '**\bin\**\*.pdb'
          PublishSymbols: false
          SymbolServerType: TeamServices

      - task: PublishPipelineArtifact@1
        displayName: Publish Umbraco Pipeline Artifact
        inputs:
          targetPath: $(build.artifactstagingdirectory)
          artifactName:  $(BuildParameters.ArtifactName)