trigger:
- none


#--------------Variables---------------------------------------------------------
variables:
- group: BAETestVarGroup


#--------------Resources---------------------------------------------------------
resources:
  repositories:
  - repository: githubRepo
    type: github
    ref: '$(github_branch)'
    endpoint: 'anilkdhiman6'
    name: 'anilkdhiman6/BAEExample'



#--------------Stages---------------------------------------------------------
stages:
- stage: A
  displayName: 'Deploy resource to azure'
  jobs:
    - job: Job_A1
      displayName: Agent job A1
      pool:
        vmImage: vs2017-win2016
      steps:
      - checkout: githubRepo
      - task: AzureResourceGroupDeployment@2
        inputs:
          azureSubscription: 'Free Trial(2bc5ea50-1ac3-4e14-8d64-69f2fc360272)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroup)'
          location: 'UK South'
          templateLocation: 'Linked artifact'
          csmFile: 'BAETest-ArmTemplates\baetest-template.json'
          csmParametersFile: 'BAETest-ArmTemplates\baetest-parameters.json'
          deploymentMode: 'Incremental'
          deploymentOutputs: 'armoutputs'