trigger:
- none

variables:
- group: 'BAETestVarGroup'


#--------------Resources---------------------------------------------------------
resources:
  repositories:
  - repository: githubRepo
    type: github
    ref: 'master'
    endpoint: 'anilkdhiman6'
    name: 'anilkdhiman6/BAEExample'


#--------------Stages---------------------------------------------------------
stages:
- stage: A
  displayName: 'Create Function App Resource in Azure'
  jobs:
  - template: CreateFunctionApp.yml
    parameters:
        subscriptionName: '$(subscriptionName)'
        subscriptionId: '$(subscriptionId)'
        resourceGroup: '$(resourcegroupname)'
        serverfarms_ASP_externalid: '$(serverfarms_ASP_externalid)'
        sites_fa_name: '$(sites_fa_name)'